version: "3.8"
services:
  app:
    image: your-dockerhub-username/your-backend-image:latest
    container_name: your-backend-container-name
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - /var/lib/your-project/assets:/app/assets
    environment:
      # App Config
      - APP_PORT=3000
      - PORT=5000
      - APP_SALT=your_salt_value
      - APP_ENV=production
      - APP_TIMEZONE=UTC
      - APP_LOCAL_TIMEZONE=Asia/Phnom_Penh

      # Seed Key
      - SEED_KEY=your_seed_key_here

      # JWT
      - JWT_SECRET=your_jwt_secret
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret

      # MongoDB
      - MONGO_URI=mongodb://your_mongo_user:your_mongo_password@mongodb:27017/your_db_name?authSource=admin

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      # DigitalOcean Spaces (if used)
      - DO_SPACES_KEY=your_spaces_key
      - DO_SPACES_SECRET=your_spaces_secret
      - DO_SPACES_ENDPOINT=nyc3.digitaloceanspaces.com
      - DO_SPACES_NAME=your_space_name
      - DO_SPACES_REGION=us-east-1

      # AWS S3 (if used)
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_REGION=ap-southeast-2
      - AWS_S3_BUCKET_NAME=your_s3_bucket

      # Storage Config
      - USE_STORAGE=LOCAL # or S3 / SPACES
      - LOCAL_STORAGE_PATH=/app/assets
      - LOCAL_STORAGE_BASE_URL=https://your.domain.com/assets

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongo_user
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
